# secret_dockerhub.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app
spec:
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      # specifiy the docker-registry secret to be accessed
      imagePullSecrets:
        - name: docker-hub-private
      containers:
      - name: secret-app
        # of course you need an own private repository
        # to pull and change the name accordingly
        image: seblum/private:cat-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80