# services_backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendflask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backendflask
  template:
    metadata:
      labels:
        app: backendflask
    spec:
      containers:
      - name: backendflask
        image: seblum/mlops-public:backend-flask
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backendflask
spec:
  # send traffic to any pod that matches the label
  type: ClusterIP # does not need to be specified
  selector:
    app: backendflask
  ports:
    # port the service is associated with
  - port: 5001
    # port to access targeted by the access
    # in our case has to be the same as in backendflask.
    targetPort: 5000