# secrets.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets
spec:
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
    spec:
      volumes:
        # get the secret from a volume
        - name: secret-vol
          secret:
            # the name of the secret we created earlier
            secretName: mysecret-from-cli
      containers:
      - name: secrets
        image: busybox
        volumeMounts:
          - mountPath: /etc/secrets
            name: secret-vol
        env:
          # nane of the secret in the container
          - name: CUSTOM_SECRET
            # get the secret from an environment variable
            valueFrom:
              secretKeyRef:
                # name and key of the secret we created earlier
                name: mysecret-from-file
                key: secret
        command:
          - "sleep"
          - "3600"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"