# pod.yaml
apiVersion: v1
# specify which kind of configuration this is
# lets configure a simple pod
kind: Pod
# metadata will be explained later on in more detail
metadata:
  name: hello-world
  labels:
  name: hello-world
spec:
  # remember: a pod is a selection of one or more containers
  # we could therefore specify multiple containers
  containers:
    # specify the container name
  - name: hello
  # specify which container image should be pulled
  image: seblum/mlops-public:cat-v1
  # ressource configurations will be handled later as well
  ressources:
    limits:
    memory: "128Mi"
    cpu: "500m"
  # specify the port on which the container should be exposed
  # similar to the imperative approach
  ports:
      ContainerPorts: 80