# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-deployment
  template:
    metadata:
      labels:
        app: monitoring-deployment
    spec:
      containers:
      - name: monitoring-deployment
        image: "grafana/grafana:latest"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
