# resource-management.yaml
apiVersion: apps/v1
# specify that we want a deployment
kind: Deployment
metadata:
  name: rm-deployment
spec:
  # specify number of replicas
  replicas: 3
  selector:
    matchLabels:
      app: rm-deployment
  template:
    metadata:
      labels:
        app: rm-deployment
    spec:
      containers:
      - name: rm-deployment
        image: seblum/mlops-public:cat-v1
        requests:
          memory: "512Mi"
          cpu: "1000m"
        # Limits
        limits:
          memory: "128Mi"
          cpu: "500m"
        ports:
        - containerPort: 5000